<?php $this->layout('layouts/app', ['tab' => 'users']) ?>

<h3>Users</h3>
<br>
<table style="width:100%">
    <tr>
        <th>Username</th>
        <th>Email</th>
        <th>Password</th>
        <th>Gender</th>
    </tr>
    <tr>
        <td>Zee</td>
        <td>zee@ku.th</td>
        <td>zee1234</td>
        <td>Male</td>
    </tr>
    <tr>
        <td>Bob</td>
        <td>bob@ku.th</td>
        <td>bob1234</td>
        <td>Male</td>
    </tr>
    <tr>
        <td>Viva</td>
        <td>viva@ku.th</td>
        <td>viva1234</td>
        <td>Female</td>
    </tr>
    <tr>
        <td>Fit</td>
        <td>fit@ku.th</td>
        <td>fit1234</td>
        <td>Female</td>
    </tr>
    <tr>
        <td>Tee</td>
        <td>tee@ku.th</td>
        <td>tee1234</td>
        <td>Male</td>
    </tr>
    <tr>
        <td>Bell</td>
        <td>bell@ku.th</td>
        <td>bell1234</td>
        <td>Female</td>
    </tr>
    <tr>
        <td>Non</td>
        <td>non@ku.th</td>
        <td>non1234</td>
        <td>Male</td>
    </tr>
    <tr>
        <td>Ing</td>
        <td>ing@ku.th</td>
        <td>ing1234</td>
        <td>Male</td>
    </tr>
    <tr>
        <td>Zen</td>
        <td>zen@ku.th</td>
        <td>zen1234</td>
        <td>Male</td>
    </tr>
    <tr>
        <td>Mook</td>
        <td>mook@ku.th</td>
        <td>mook1234</td>
        <td>Female</td>
    </tr>
</table>
<hr class="under-line">